[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['vite build', 'node esbuild.config.js']

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'