[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm ci --omit=dev --include=optional']

[phases.build]
cmds = ['npm ci', 'npm run build']

[start]
cmd = 'NODE_ENV=production npm run start'